apiVersion: v1
kind: Pod 
metadata:
    name : danny
    labels: 
      env: UAT-env
      app: my-pod
    namespace: uat 
spec: 
  containers: 
  - name: danny
    image: httpd
    ports: 
     -  name: http
        containerPort: 80
  - name: danny
    image: tomcat
    ports: 
     -  name: http
        containerPort: 80      