apiVersion: v1
kind: Pod
metadata: 
    name: eks-ms-pod
    labels: 
      env: uat-env
      app: eks-ms-app
    namespace: uat
spec: 
  containers:
    - name: eks-ms-nginx-instance
      image: nginx
      ports:
        - name: http
          containerPort: 80
    - name: eks-ms-tomcat-instance
      image: tomcat
      ports:
        - name: java
          containerPort: 8080