apiVersion: v1
kind: Service
metadata:
  name: eks-ms-pod-service
  labels:
    env: uat-env
    app: eks-ms-app 
  namespace: uat #<ns-name>
spec:
  type: NodePort
  selector:
    app: eks-ms-app #[app: eb-ms-app]
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: httpd
      protocol: TCP
      port: 8080
      targetPort: 8080
